spring.application.name=emastery
server.port=${SERVER_PORT:8080}

imthang.jwt.base64-secret=${JWT_SECRET}
imthang.jwt.access-token-validity-in-seconds=${JWT_ACCESS_TOKEN_EXP}
imthang.jwt.refresh-token-validity-in-seconds=${JWT_REFRESH_TOKEN_EXP}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update